name       : haskell-roman-numerals
version    : 0.5.1.5
release    : 1
source     :
    - https://hackage.haskell.org/package/roman-numerals-0.5.1.5/roman-numerals-0.5.1.5.tar.gz : b9c7195b69b1662a286d2c28a55fafdcb693c522ba5eb54a11b1d0a4e92eaa81
license    : BSD-3-Clause
component  : programming.haskell
summary    : Parsing and pretty printing of Roman numerals
description: |
    Parsing and pretty printing of Roman numerals
builddeps  :
    - haskell-cabal-install
    - haskell-base-unicode-symbols-devel
    - haskell-text-devel
rundeps    :
    - devel:
        - haskell-base-unicode-symbols-devel
        - haskell-text-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
